- name: Check subscription status and enabled subscriptions
  hosts: all
  tasks:
    - name: Check status
      shell:
        cmd: subscription-manager status
      register: subscription

    - debug: var=subscription.stdout_lines
        
    - name: Check status
      raw: subscription-manager repos --list-enabled
